name: SISMIP_BACKEND-CI
on:
  push:
    branches: 
      - master
      - develop
#     paths:
#       - SISMIP_BACKEND/**
  pull_request:
    branches: 
      - master
      - develop
#     paths:
#       - SISMIP_BACKEND/**
jobs:
  teste:
    name: Teste
    runs-on: ubuntu-lastest
    defaults:
      run:
        working-directory: ./SISMIP_BACKEND
    env:
      PORT: 3000
      NODE_ENV: dev  
      MONGO_URL: mongo_url
    steps:
      - name: Init pre set
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: npm build --if-present
      - run: npm start --if-present
        

 
